# Generated by Django 4.1.5 on 2023-01-23 08:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tackler', '0002_alter_ticket_user_id_alter_ticket_replies_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket_Replies',
            new_name='Ticket_Comments',
        ),
    ]
