# Generated by Django 4.1.5 on 2023-01-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tackler', '0003_rename_ticket_replies_ticket_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='resolved',
            new_name='IsOpen',
        ),
    ]
