# Generated by Django 4.1.5 on 2023-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tackler', '0004_rename_resolved_ticket_isopen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='IsOpen',
            new_name='is_open',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ticket_comments',
            old_name='ticket_id',
            new_name='ticket',
        ),
        migrations.RenameField(
            model_name='ticket_comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='relevance',
            field=models.CharField(max_length=25),
        ),
    ]
