# Generated by Django 4.1.5 on 2023-01-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tackler', '0005_rename_isopen_ticket_is_open_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='topic',
            new_name='type',
        ),
    ]
