# Generated by Django 4.1.5 on 2023-02-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tackler', '0007_ticket_assigned_users_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket_comments',
            name='reply_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
