# Generated by Django 4.1.5 on 2023-02-09 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tackler', '0008_alter_ticket_ticket_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_users',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
