# Generated by Django 4.1.5 on 2023-02-09 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tackler', '0009_remove_ticket_assigned_users_ticket_assigned_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
